sonar.projectKey=rag-pdf-app
sonar.projectName=rag-pdf-app
sonar.projectVersion=0.1.0
sonar.organization=skluba

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,\
  **/*.pyc,\
  **/dist/**,\
  **/build/**,\
  **/.venv/**,\
  **/venv/**,\
  Dockerfile,\
  docker-compose.yml

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=reports/junit-report.xml
